import Head from "next/head";
import { useState } from "react";

import Countries from "@/components/countries/Countries";
import Region from "@/components/region/Region";
import SearchBar from "@/components/search-bar/SearchBar";

export default function Home() {
  const [query, setQuery] = useState("");
  const [selectedRegion, setSelectedRegion] = useState("");

  return (
    <>
      <Head>
        <title>Next Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-8 md:my-12 md:px-12 xl:px-24">
        <div className="px-4 max-w-[1600px] mx-auto md:flex md:px-1 items-center justify-between">
          <SearchBar
            query={query}
            setQuery={setQuery}
            setSelectedRegion={setSelectedRegion}
          />
          <Region
            selectedRegion={selectedRegion}
            setSelectedRegion={setSelectedRegion}
            setQuery={setQuery}
          />
        </div>
      </div>
      <Countries selectedRegion={selectedRegion} query={query} />
    </>
  );
}
